### ISSUE TITLE
Epic: Authorization

### ISSUE THREAD

**Issue by gorlobarloga** [ita-social-projects/TeachUA#1351]
Features list:

- [x] Create new user
- [x] Authorization for registered user
- [x] Login through Google account
- [x] Restore Password
- [x] Profile
- [x] Regular Registration
