### ISSUE TITLE
[Challenge] View Challenge Page (New Design)

### ISSUE THREAD

**Issue by gorlobarloga** [ita-social-projects/TeachUA#1367]
As an admin I want to have an access to a list of the changes and their settings so that to check and control site's content.

### Description

![image](https://user-images.githubusercontent.com/51957186/164647840-37c7ff11-5cc2-4e8d-9036-2e61746effd3.png)

### Acceptance Criteria

- When user access "Aдміністрування"/"Челенджі", "Челенджі" page with previously created challenges should be shown
- Table with challenges should contain "Порядковий номер", "Назва", "Заголовок", "Активний", "Управління" columns
- Navigation bar should be provided.
- "Додати челендж" button that invokes editor for a new challenge should be provided.
- "Активний" column should reflect current challenge state.
- "Управління” column should provide an ability to open the list of tasks from selected challenge.
- "Управління" column should provide an ability to remove selected challenge.
- "Управління" column should provide an ability to edit selected challenge.

**Epic link**
Epic #111

### Tasks

- [ ] Remove database id from table
- [ ] Edit should invoke an editor.
- [ ] Use pagination from clubs page and remove English from lines amount lookup.
- [ ] Add "Активний" column.
- [ ] Remove "Завдання" option from "Aдміністрування" menu.
- [ ] Change "Дія" to  "Управління"
- [ ] Add "До Завдань" option to "Управління" сolumn.
