### ISSUE TITLE
[Challenge] Create Challenge (New Design)

### ISSUE THREAD

**Issue by gorlobarloga** [ita-social-projects/TeachUA#1371]
As an admin I want to have an ability to define content of a selected and new challenge so that to control the site's content.

**Description**
![image](https://user-images.githubusercontent.com/51957186/166440827-07b07fb6-093c-4427-8ede-50621ff5dc06.png)

![image](https://user-images.githubusercontent.com/51957186/166441145-d3a426ce-2a4d-449a-8785-d7d2e953a39e.png)

### Acceptance Criteria

- "Додати челендж" modal window with empty "Назва", "Заголовок", "Опис", "Фото" fields and "Порядковий номер" defaulted to "1" shall appear when "Додати" челендж is selected. 
- "Редагувати челендж" modal window with previously defined challenge content shall appear for selected item when "Редагувати" is selected.
- User is able to set "Порядковий номер", "Назва", "Заголовок", "Опис", "Фото"  for a new challenge.
- User is able to change "Порядковий номер", "Назва", "Заголовок", "Опис", "Фото" for previously created challenge.
- Changes are saved and "Переглянути" button is enabled when "Зберегти" is selected.
- Uploaded photo with size that is bigger then 1 Mb shall be compressed to 1 Mb. File picker window shall contain only JPG and PNG files.
- "Зберегти" button shall be disabled while all the mandatory fields are not set. Mandatory fields are:  "Назва", "Заголовок", "Опис", "Фото".
- "Назва", "Заголовок", "Опис" fields shall be validates as described below upon "Зберегти" button is clicked. Each validation message shall appear from a new line.
- "Управління" column shall provide an ability to remove related task through “Видалити” button.
After clicking the "Delete" button a pop-up window should appear with "Видалити чеоендж?" text and "Ні" and "Так" buttons.
"Управління" column shall provide an ability to open an editor for related task through “Редагувати” button.
- Fields from validation errors shall be highlighted with red border.
- Message about challenge creation shall appear upon successful save operation for a new challenge.
- Message about challenge change shall appear upon successful save operation for existing challenge.

**Validation rules**

|Condition |Message|
|---|---|
|Опис > 25000 |Поле "Опис" може містити максимум 25000 символів|
|Назва <3 OR >30|Поле "Назва" може містити мінімум 3 та максимум 30 символів.|
|Заголовок <5 OR 100>|Поле "Заголовок" може містити мінімум 5 та максимум 100 символів.|

**Epic link** #111

### Tasks 

- [ ] Implement new editor in modal window.
- [ ] Fix photo change.
- [ ] Fix validation messages.
