### ISSUE TITLE
[Challenge] View challenge - Sorting (New Design)

### ISSUE THREAD

**Issue by gorlobarloga** [ita-social-projects/TeachUA#1375]
As an admin I want to apply sort order for the challenge list, so that to access a specific challenge and check challenge sequence.

**Description**

![image](https://user-images.githubusercontent.com/51957186/165526621-3555249d-5a37-4a0e-87c8-7c526237b197.png)

### Acceptance Criteria

- The list of challenges shall be sorted by name when user clicks "Назва" column header, by sequence number when admin clicks "Порядковий номер", by summary when user clicks "Заголовок" and by status when  user click to the “Активний” column. By first click  ascending sort order shall apply. 
- Sort order shall change by the following clicks on table header.
- Sort sign (triangle) shall appear for sort to the right of the column name. It shall reflect the sorting order (descending - top-down, ascending - upward).

**Epic link** #111

### Tasks 
- [ ] Provide user with ability to apply sorting by clicking column headers.
- [ ] Provide sorting algorithm for challenges by name and sequence number.
- [ ] Provide sort order identifier.
