### ISSUE TITLE
[Challenge] Tasks - Tasks list table (New Design)

### ISSUE THREAD

**Issue by gorlobarloga** [ita-social-projects/TeachUA#1378]
As an Admin I want to access the list of tasks and their settings so that to check created tasks.

**Description**
![image](https://user-images.githubusercontent.com/51957186/165706207-5d9327ff-f080-45ec-81d0-9e9f8f1a30f7.png)

![image](https://user-images.githubusercontent.com/51957186/165706418-bfb5bd56-19e6-4d1e-8a4a-cd7c709a37bd.png)

### Acceptance Criteria

- Tasks table shall provide "Назва", "Челендж", "Активний", "Дата завдання", "Управління" columns.
- The system shall provide an ability to open an Editor for a new task through "Додати завдання" button.
- "Управління" column shall provide an ability to remove related task.
- "Управління" column shall provide an ability to open an editor for related task.
- "Активний" column shall reflect current task state.
- "Челендж" column shall reflect related challenge name.
- Navigation bar shall be provided.
- The system shall provide an ability to open and Editor for already created task through.
- Tasks table title shall identify provide a challenge name if applicable.
- The system shall provide an ability to return to the challenge list.

**Epic link** #111

### Tasks 
- [ ] Provide column with task status.
- [ ] Provide column with challenge name.
- [ ] Provide title based on selected challenge.
- [ ] Adjust navigation bar to be consistent with the one on clubs page.
