### ISSUE TITLE
[Challenge] Task - Sorting (New Design) 

### ISSUE THREAD

**Issue by gorlobarloga** [ita-social-projects/TeachUA#1382]
As an Admin I want to apply sort order for the tasks list, so that to quickly access a specific task and check tasks sequence.

**Description**
![image](https://user-images.githubusercontent.com/51957186/165925317-cbc629fd-3afa-4fc4-a38c-f80942d7cbe0.png)

### Acceptance Criteria
The list of tasks shall be sorted by name when user clicks "Назва" column header and by date when user clicks "Дата Завдання" . By first click ascending sort order shall apply.
Sort order shall be change by the following clicks on table header.
Sort sign (triangle) shall appear for sort by column. It shall reflect the sorting order (descending - top-down, ascending - upward).

**Epic link**  #111 

### Tasks  

- [ ] Provide user with ability to apply sorting by clicking column headers.
- [ ]  Provide sorting algorithm for challenges by name and sequence number.
- [ ]  Provide sort order identifier.
- [ ]
