### ISSUE TITLE
[Challenge] Create Challenge - Registration

### ISSUE THREAD

**Issue by gorlobarloga** [ita-social-projects/TeachUA#1418]
**As an Admin I want to set a registration for a challenge so that users have an ability to register to a challenge on its page.**

**Description:**
![image](https://user-images.githubusercontent.com/51957186/171147959-bfc68cea-2865-4acb-85a9-895fc1a5efa1.png)

![image](https://user-images.githubusercontent.com/51957186/171148069-d0684a44-2259-4a73-97a8-4ffc0212e1dd.png)

![image](https://user-images.githubusercontent.com/51957186/171148168-a1e68679-582e-491e-ab0b-948f9d0b0731.png)

![image](https://user-images.githubusercontent.com/51957186/171148238-9332dc45-49ab-4fe1-b0ac-a958872424e6.png)

### Acceptance Criteria

- Challenge setup shall provide flag "Додати реєстрацію".
- "Посилання реєстрації" field shall be visible and mandatory only when "Додати реєстрацію" flag is active.
- System shall provide "Реєстрація" button on challenge page when registration flag is activated in challenge setup.
- Related to challenge registration form shall be opened when user clicks "Реєстрація" button.
- System shall provide ability to close registration form.

**Epic link**  #111

### Tasks 
- [ ] Provide ability to store registration flag.
- [ ] Provide ability to enter and save registration link if flag is active.
- [ ] Update challenge page with registration button and iframe with registration form according to challenge preferences.
