### ISSUE TITLE
[Certificates] Issuance of Certificates - Certificate load

### ISSUE THREAD

**Issue by gorlobarloga** [ita-social-projects/TeachUA#1447]
**As a user I want to load the obtained certificate so that I have confirmation of the passed challenge.**

![image](https://user-images.githubusercontent.com/51957186/174457790-129e3428-7051-42e3-8495-d3b28d9dcfbe.png)
![image](https://user-images.githubusercontent.com/51957186/174457796-c1ef7a8d-a5c4-48a4-8bc7-8e6762ab97b6.png)
![image](https://user-images.githubusercontent.com/51957186/174457804-41b5654c-2326-4994-be7f-e81587bacccc.png)

### Acceptance Criteria

- System shall provide "Сертифікати" main menu option.
- "Сертифікати" page shall be opened when user clicks "Cертифікати" main menu option. 
- "Сертифікати" page shall contain the list lookup of challenge names, a field to enter a name and "Отримати сертифікат" button. 
- "Отримати сертифікат" button shall be disabled when name field is empty. 
- System shall generate and load certificate when user clicks "Отримати сертифікат" and corresponding issued_certificate record exists. System shall generated and load certificate shall be loaded and issued certificate record shall be added if successful test results exists. For this Google Forms API shall be requested when issued_certificate record is not found. 
- If results are not found, system shall reflect notification message “Сертифікат не знайдено. Перевірте обраний челлендж та введене ім’я.”
- Loaded certificate shall contain name, date and certificate number of the corresponding record and view according to template. 

### Tasks 

- [ ] Develop a page of certificate issuance.
- [ ] Provide mechanism of certificate search.
- [ ] Provide mechanism of ad-hoc test results check.
- [ ] Generate PDF based on certificate data and load it.

**Epic link** #1437
